### ISSUE TITLE
SSRF的代码感觉有些问题

### ISSUE THREAD

**Issue by geekmc** [JoyChou93/java-sec-code#2]
/HttpURLConnection
访问：http://localhost:8080/ssrf/HttpURLConnection?url=file:///etc/passwd
会报异常：java.lang.ClassCastException: sun.net.www.protocol.file.FileURLConnection cannot be cast to java.net.HttpURLConnection
修改添加代码：
 URL u = new URL(null,url,new sun.net.www.protocol.file.Handler());
任然报错，请作者指点一二

**Comment by JoyChou93** [comment]
HttpURLConnection类导致的SSRF，默认只支持HTTP协议，所以file协议会报错。

你可以要用file协议，你可以去试其他的非HTTP打头的类造成的SSRF。

**Comment by geekmc** [comment]
目前支持file协议的是不是只有urlConnection和URL类的openStream方法

**Comment by JoyChou93** [comment]
@geekmc 能用file读取文件不报错的就可以，这个自行测试吧。
