### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by godzeo** [JoyChou93/java-sec-code#23]
老哥你这个，是我不会配还是怎么的，就是很奇怪，

你这个必须登录嘛，要不就会一直在login

但是你那个在线的地址，和docker 我都试了一下，admin都登陆不了，不能用，我看下源码，登陆功能是空的，有点不懂

**Comment by godzeo** [comment]
老哥你这docker数据库里面 账户密码也不对啊。。。我一直没明白，这是咋用的

![image](https://user-images.githubusercontent.com/64398024/89101424-5c499180-d432-11ea-9483-4f2a5acfbec6.png)

**Comment by JoyChou93** [comment]
admin/admin123
joychou/joychou123

**Comment by godzeo** [comment]
你给的那个在线demo 和docker  都点登陆没反应。。。这是为啥啊
我用的就是admin/admin123
joychou/joychou123

**Comment by JoyChou93** [comment]
https://code.jquery.com/jquery-3.4.1.min.js 无法访问导致登录无法使用

**Comment by godzeo** [comment]
是这个问题，我把静态资源放到本地了
