### ISSUE TITLE
MySQL commands to support running JavaSecCode 

### ISSUE THREAD

**Issue by dtpoirot** [JoyChou93/java-sec-code#24]
Please consider using some account other than 'root', such as 'joychou'. I use MySQL to support a number of services.

The following are commands I use to create the environment to support running JavaSecCode. This list may not be complete.

-- MySQL dump 10.13  Distrib 5.7.31, for Linux (x86_64)
--
-- Host: localhost    Database: java_sec_code
-- ------------------------------------------------------
-- Server version       5.7.31-0ubuntu0.18.04.1

--
-- Pedantic, aren't we
--

USE mysql;

--
-- Remove, create user, Super User
--

DROP USER IF EXISTS `joychou`@`localhost`;
CREATE USER 'joychou'@'localhost' IDENTIFIED BY 'woshishujukumima';
GRANT ALL PRIVILEGES ON *.* TO 'joychou'@'localhost' IDENTIFIED BY 'woshishujukumima';

--
-- Remove, create database
--

DROP DATABASE IF EXISTS java_sec_code;
CREATE DATABASE java_sec_code;
USE java_sec_code;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `java_sec_code.users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `username` varchar(16) NOT NULL,
  `password` varchar(32) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `users`
--

LOCK TABLES `users` WRITE;
INSERT INTO `users` VALUES (1,'joychou','password');
UNLOCK TABLES;

**Comment by JoyChou93** [comment]
Thank you for your issue. But I won't fix it. You can change the code by yourself.

**Comment by dtpoirot** [comment]
My mistake.

Apologies.
