### ISSUE TITLE
docker 环境mysql 连接 报错 Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by jax777** [JoyChou93/java-sec-code#25]
Public Key Retrieval is not allowed

**Comment by FKK921** [comment]
Me too.

**Comment by FKK921** [comment]
1、修改pom.xml中mysql版本与实际版本一致。
2、修改application.properties里面jdbc为allowPublicKeyRetrieval=true，再加上characterEncoding=utf8

**Comment by JoyChou93** [comment]
本地测试可修改application.properties里的AllowPublicKeyRetrieval为allowPublicKeyRetrieval。
docker环境我找时间重新发布一下。
