### ISSUE TITLE
关于Cookies部分意图的疑问

### ISSUE THREAD

**Issue by R3col** [JoyChou93/java-sec-code#30]
大佬你好，我想请问一下Cookies部分代码的意图是什么，左思右想也没有想到 = =，希望大佬能指点一二

**Comment by JoyChou93** [comment]
某些应用获取用户身份信息可能会直接从cookie中直接获取明文的nick，导致越权问题。具体写法可能有[Cookies代码](https://github.com/JoyChou93/java-sec-code/blob/master/src/main/java/org/joychou/controller/Cookies.java)里的几种情况。

**Comment by R3col** [comment]
理解了，感谢师傅的指点。

**Comment by R3col** [comment]
> 某些应用获取用户身份信息可能会直接从cookie中直接获取明文的nick，导致越权问题。具体写法可能有[Cookies代码](https://github.com/JoyChou93/java-sec-code/blob/master/src/main/java/org/joychou/controller/Cookies.java)里的几种情况。

理解了。感谢JoyChou师傅解答！
