### ISSUE TITLE
crlf injection is wrong

### ISSUE THREAD

**Issue by HYWZ36** [JoyChou93/java-sec-code#34]
Hello, when I learn it, I found that CRLF Injection did not work, as follows:
![image](https://user-images.githubusercontent.com/27775281/114266235-cc7bce80-9a27-11eb-96e1-6d5c0e708a3e.png)
Can you help me？

**Comment by JoyChou93** [comment]
Java 1.7/1.8 no CRLF vulns (test in Java 1.7/1.8)
