### ISSUE TITLE
Java 1.7/1.8 no CRLF vulns (test in Java 1.7/1.8)

### ISSUE THREAD

**Issue by HYWZ36** [JoyChou93/java-sec-code#35]
Yes, I apply it in Java 11, and it still can not work. Can you help me?

Java 1.7/1.8 no CRLF vulns (test in Java 1.7/1.8)

_Originally posted by @JoyChou93 in https://github.com/JoyChou93/java-sec-code/issues/34#issuecomment-817122824_

**Comment by JoyChou93** [comment]
Therefore, there should be no CRLF vulnerabilities in Java. Generally, CRLF exists in NGINX and PHP.
