### ISSUE TITLE
jolokia/list访问不到

### ISSUE THREAD

**Issue by HYWZ36** [JoyChou93/java-sec-code#36]
那个，在复现actualtor漏洞，xxx/jolokia/list访问为啥没正确页面呢？jdk版本没问题的。
![image](https://user-images.githubusercontent.com/27775281/114823676-6cee3c00-9df6-11eb-8526-019954927fdd.png)

**Comment by JoyChou93** [comment]
在application.properties配置里修改`endpoints.enabled`为 true。

```xml
endpoints.enabled=true
```
