### ISSUE TITLE
sqli的url有点小问题，应当是jdbc/vuln?username=

### ISSUE THREAD

**Issue by FeatherStark** [JoyChou93/java-sec-code#46]
https://github.com/JoyChou93/java-sec-code/blob/master/src/main/java/org/joychou/controller/SQLI.java#L46

应当是http://localhost:8080/sqli/jdbc/vuln?username=joychou

源代码：
```
    /**
     * Vuln Code.
     * http://localhost:8080/sqli/jdbc/vul?username=joychou
     *
     * @param username username
     */
    @RequestMapping("/jdbc/vuln")
```

**Comment by JoyChou93** [comment]
谢谢提醒，欢迎提交Pull Requests。
