### ISSUE TITLE
文件上传功能，跳转到upload页面路径错误。

### ISSUE THREAD

**Issue by Ckmount** [JoyChou93/java-sec-code#5]
file上传页面
![image](https://user-images.githubusercontent.com/18661632/50957965-865afc00-14fa-11e9-947d-a6979765f30c.png)
跳转后项目名丢失。
![image](https://user-images.githubusercontent.com/18661632/50958050-c3bf8980-14fa-11e9-8ff6-1a3d4927391a.png)
修改/java-sec-code-master/src/main/resources/templates/upload.html 代码，删除/file/
![image](https://user-images.githubusercontent.com/18661632/50958254-3f213b00-14fb-11e9-89c0-a186986861c3.png)

**Comment by JoyChou93** [comment]
Thanks.

**Comment by Ckmount** [comment]
> 谢谢。

没事，项目挺好啊，希望一直更新下去。
