### ISSUE TITLE
docker 安装启动后，端口访问不到。

### ISSUE THREAD

**Issue by jielansudo** [JoyChou93/java-sec-code#69]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/50390082/223354846-cbce58c6-beec-4d8e-a156-819bfba1510a.png">

启动成功了，但是本地无法访问

<img width="611" alt="image" src="https://user-images.githubusercontent.com/50390082/223354940-641541d2-5802-472a-b167-46774889fe86.png">

**Comment by JoyChou93** [comment]
`git pull` 试试最新版本的代码。docker也`docker-compose pull`下。我本地Mac测试没问题。
