### ISSUE TITLE
Please update lombok

### ISSUE THREAD

**Issue by danielpoirot** [JoyChou93/java-sec-code#70]
Please consider upgrading lombok from version 1.18.16 to version 1.18.20

I get a compiler error:
"Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x3816efab) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x3816efab"

**Comment by JoyChou93** [comment]
What's your JDK version?

**Comment by JoyChou93** [comment]
> Please consider upgrading lombok from version 1.18.16 to version 1.18.20
> 
> I get a compiler error: "Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x3816efab) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x3816efab"


What's your JDK version?

**Comment by danielpoirot** [comment]
I have always used OpenJDK 11

 

Should I upgrade? 

 

Thank you for your note!

 

Best regards,

*	Dan
